SET NOCOUNT ON

DECLARE @NOMEBANCO VARCHAR(100);
DECLARE @NOMETABELA VARCHAR(100);
DECLARE @TABELAEXISTE smallint;
DECLARE @VALORMINIMO FLOAT; -- valor minimo de fragmentacao
DECLARE @NOMEINDICE VARCHAR(100);
DECLARE @FRAGMENTACAO NUMERIC(15,5);
DECLARE @CHAVE INT;
DECLARE @SOMENTECONSULTA INT;
DECLARE @NOMES TABLE  (CHAVE INT, NOMETABELA VARCHAR(100), TABELAEXISTE SMALLINT, NOMEINDICE VARCHAR(100), FRAGMENTACAO NUMERIC(15,5));
DECLARE @NOME VARCHAR(50);

DECLARE @TOTAL SMALLINT = 0;
DECLARE @CONT SMALLINT = 0;

-- SETAR PARAMETROS
SELECT @NOMEBANCO=DB_NAME();

SET @VALORMINIMO=0.10; -- Porcentagem de fragmentação
SET @SOMENTECONSULTA=0; -- 1 somente consulta    0 - Executa a Desfragmentação

DECLARE C_NOMETABELA CURSOR FOR 
 select NOMETABELA FROM TABELASISTEMA;
OPEN C_NOMETABELA;

SELECT @TOTAL=COUNT(TABELASISTEMA.TABELASISTEMA) FROM TABELASISTEMA;

FETCH NEXT FROM C_NOMETABELA INTO @NOMETABELA;
WHILE @@FETCH_STATUS=0
BEGIN
	SET @CONT= @CONT+1;

	SELECT @TABELAEXISTE=count(*) FROM SYSOBJECTS WHERE XTYPE = 'U' AND NAME = @NOMETABELA;

	IF @TABELAEXISTE<>0
	BEGIN
	   SELECT
			@NOME=i.name 
	   FROM
	   sys.dm_db_index_physical_stats(DB_ID(@NOMEBANCO), OBJECT_ID(@NOMETABELA), NULL, NULL, NULL) phystat 
	   INNER JOIN sys.indexes i ON (i.OBJECT_ID = phystat.OBJECT_ID AND i.index_id = phystat.index_id)
	   WHERE 
	   phystat.avg_fragmentation_in_percent >= @VALORMINIMO 
	   AND OBJECT_ID(@NOMETABELA) IS NOT NULL;

	   if LTRIM(@NOME) <> ''
	   begin
		   DECLARE C_ESTATISTICA CURSOR FOR
		   SELECT
		   i.name,
		   avg_fragmentation_in_percent
		   FROM
		   sys.dm_db_index_physical_stats(DB_ID(@NOMEBANCO), OBJECT_ID(@NOMETABELA), NULL, NULL, NULL) phystat 
		   INNER JOIN sys.indexes i ON (i.OBJECT_ID = phystat.OBJECT_ID AND i.index_id = phystat.index_id)
		   WHERE 
		   phystat.avg_fragmentation_in_percent >= @VALORMINIMO 
		   AND OBJECT_ID(@NOMETABELA) IS NOT NULL;
		   OPEN C_ESTATISTICA;

		   SET @CHAVE=0

		   FETCH NEXT FROM C_ESTATISTICA INTO @NOMEINDICE, @FRAGMENTACAO;
		   WHILE @@FETCH_STATUS=0
		   BEGIN
			   SET @CHAVE=@CHAVE+1;
			   INSERT INTO @NOMES (CHAVE, NOMETABELA, TABELAEXISTE, NOMEINDICE, FRAGMENTACAO)
			   VALUES (@CHAVE, @NOMETABELA, 1, @NOMEINDICE, @FRAGMENTACAO);

			   IF @SOMENTECONSULTA=0
			   BEGIN
				  PRINT 'Select 1 WAITFOR DELAY ''00:00:05''';

				  PRINT 'DECLARE @NOMEBANCO VARCHAR(100) = DB_NAME();'
				  print 'DBCC INDEXDEFRAG (@NOMEBANCO,'+@NOMETABELA+','+@NOMEINDICE+');'
				  PRINT 'GO'
			
				  --DBCC INDEXDEFRAG (@NOMEBANCO, @NOMETABELA, @NOMEINDICE);
			   END

			   FETCH NEXT FROM C_ESTATISTICA INTO @NOMEINDICE, @FRAGMENTACAO;
		   END

		   CLOSE C_ESTATISTICA;
		   DEALLOCATE C_ESTATISTICA;
	   END
	END
	ELSE
	BEGIN
	   SET @CHAVE=@CHAVE+1;
	   INSERT INTO @NOMES (CHAVE, NOMETABELA, TABELAEXISTE)
	   VALUES (@CHAVE, @NOMETABELA, 0);
	END

	FETCH NEXT FROM C_NOMETABELA INTO @NOMETABELA;
END

CLOSE C_NOMETABELA;
DEALLOCATE C_NOMETABELA;

SET NOCOUNT OFF