-- para mostrar os erros
DBCC CHECKDB('NOMEBANCO') WITH NO_INFOMSGS

-- para reparar os erros
ALTER DATABASE NOMEBANCO SET SINGLE_USER
GO
DBCC CHECKDB('NOMEBANCO', REPAIR_REBUILD)
ALTER DATABASE SOUZALIMA_20170216_186 SET MULTI_USER

