set nocount on

-- Deve ser criado uma tabela chamado CONFIGTAB, com as colunas NOMEFUNCAO, NOMETABELA e NOMEFILEGROUP.

If not exists (select * from sysobjects where name='COMANDODDL' and xtype='U')
begin
    create table COMANDODDL (
        id INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
		TIPO SMALLINT, -- 0-ELIMINAR CONTRAINT FK, 1-ELIMINAR PK, 2,-CRIAR PK, 3-ELIMINAR FK, 4-CRIAR FK, 5 - CRIAR CONSTRAINT FK
		SQL NVARCHAR(MAX)    
	)
end

DECLARE @NOMEFG VARCHAR(50)

SET @NOMEFG='MODULOA'
UPDATE CONFIGTAB SET NOMEFILEGROUP=@NOMEFG WHERE NOMETABELA='TABELA1'
UPDATE CONFIGTAB SET NOMEFILEGROUP=@NOMEFG WHERE NOMETABELA='TABELA2'
UPDATE CONFIGTAB SET NOMEFILEGROUP=@NOMEFG WHERE NOMETABELA='TABELA3'

SET @NOMEFG='MODULOB'
UPDATE CONFIGTAB SET NOMEFILEGROUP=@NOMEFG WHERE NOMETABELA='TABELA5'
UPDATE CONFIGTAB SET NOMEFILEGROUP=@NOMEFG WHERE NOMETABELA='TABELA6'
UPDATE CONFIGTAB SET NOMEFILEGROUP=@NOMEFG WHERE NOMETABELA='TABELA7'


SET @NOMEFG='MODULOC'
UPDATE CONFIGTAB SET NOMEFILEGROUP=@NOMEFG WHERE NOMETABELA='TABELA8'
UPDATE CONFIGTAB SET NOMEFILEGROUP=@NOMEFG WHERE NOMETABELA='TABELA9'
UPDATE CONFIGTAB SET NOMEFILEGROUP=@NOMEFG WHERE NOMETABELA='TABELA10'